### ISSUE TITLE
unknown option '--no-minify'

### ISSUE THREAD

**Issue by stemeinke** [eadwinCode/django-compressor-parceljs#12]
Hello 
I have the package as described in the ReadMe.md file. Unfortunately I get the error unknown option '--no-minify' when calling my Django page.
in the file `<<project path>>/venv/lib/python3.8/site-packages/compressor/filters/parceljs.py line 86, in input `
Did I do something wrong?

My Python Version is 3.8.5
Django Version: 3.1.3
Parcel Version: parcel@2.0.0-beta.2

**Comment by krystofbe** [comment]
You can try the old parcel 1 which seems to support this option

`yarn global add parcel-bundler `

**Comment by stemeinke** [comment]
Thank you it works
