### ISSUE TITLE
Parcel problem when trying to manage.py compress

### ISSUE THREAD

**Issue by majormunky** [eadwinCode/django-compressor-parceljs#15]
When following the instructions to install Parcel, it installs Parcel v2, which seems not not have the same command line arguments that Parcel v1 used.  I ran into this when trying to get the "typescript directly in my django templates" example working.

You can fix this by installing parcel-bundler instead. which I guess is also known as parcel v1.

The error message that comes up when trying to use this with just parcel is:
`CommandError: An error occurred during rendering /Users/me/Desktop/code_testing/typescript/django_typescript/home/templates/home/index.html: error: unknown option '-d'`

To fix this, I did:
`sudo npm uninstall -g parcel`
`sudo npm install -g parcel-bundler`

Edit: By the way I love this package, i'm just digging into Typescript and this is the first way that makes sense to me on how to get that working in django where my ts code is in my django templates!

**Comment by eadwinCode** [comment]
Hey Josh

Thanks for your feedback
I will look into it and get back to you

Regards

**Comment by rjbullock** [comment]
Does closed mean that you can now use parcel or do you still need to use parcel-bundler?

**Comment by eadwinCode** [comment]
@rjbullock yes

**Comment by rjbullock** [comment]
Sorry, but did you mean "yes, you can use parcel" or "yes, you still need to use parcel-bunder"?
