### ISSUE TITLE
image references from Vue components

### ISSUE THREAD

**Issue by e8johan** [eadwinCode/django-compressor-parceljs#6]
When creating an img element in a Vue template, I run into two alternative scenarios:

- If I specify an absolute path, e.g. '/static/images/foo.png', parcel complains that the directory does not exist.
- If I specify a relative path, e.g. '../images/foo.png', parcel decides to compress the png to a different filename, e.g. '/foo.4055feba.png', but does not create the file in the compressed output directory.

I've also tried the '///../static/images/foo.png' trick mentioned in the css section, but to no avail (the browser simply does not load the '///../static/' png.

How do I refer to a png from a Vue component in a file.

**Comment by eadwinCode** [comment]
Can I see code implementation sample?

**Comment by e8johan** [comment]
Sure. I created something of a reference deployment of Django + Vue using the django-compressor-parceljs in this repo: https://github.com/e8johan/django-vue-example .

The error cases I describe above are found in the following branches:

**Absolute path**: https://github.com/e8johan/django-vue-example/tree/static-image, does not work as parcel bails on the following error:

```
Unable to apply ParserFilterJS (parcel build {file_name} --no-minify --no-source-maps --no-autoinstall --no-content-hash  -d {dir} --out-file {outfile})
🚨  /home/e8johan/work/django-vue-example/djangovue/todo/static/js/static/images/trashcan.png: ENOENT: no such file or directory, open '/home/e8johan/work/django-vue-example/djangovue/todo/static/js/static/images/trashcan.png'
Error: ENOENT: no such file or directory, open '/home/e8johan/work/django-vue-example/djangovue/todo/static/js/static/images/trashcan.png'
```

**Relative path**: https://github.com/e8johan/django-vue-example/tree/static-image-relative, breaks on the URL to the image being: `http://localhost:8000/trashcan.666ab798.png`, which is wrong. For instance, the compressed Javascript lives at `/static/CACHE/js/todoapp.25a9cff4dfc8.js`, so even if the file was generated (it is not), the URL is missing `/static/CACHE/images/`.

**Tripple slash**: https://github.com/e8johan/django-vue-example/tree/static-image-trippleslash, breaks as the URL (according to the _View image info..._ option is `http://static/images/trashcan.png`, i.e. the `localhost:8000` is missing in lost.

**Workaround**: https://github.com/e8johan/django-vue-example/tree/static-image-hack. I was able to come up with this hackish work-around, but it is really ugly and requires manual work in two places for each static asset, so not that pretty.

You can checkout what I did in each branch by diffing it to the `main` branch.

**Comment by eadwinCode** [comment]
Please can you add a readme on how to start your django-vue-example

**Comment by eadwinCode** [comment]
Hey Johan,
I looked at your repo and all the branches as you explained above. There
are two ways to solve the problem
 - 1. you can bind to src directly :src="*some_img_path*" where
*some_img_path*="*/static/images/trashcan.png*"
 - 2. you can upgrade your django-compressor-parceljs
<https://pypi.org/project/django-compressor-parceljs/2.3.3/> to 2.3.3 and
use continue with *static-image-trippleslash *branch

Thanks for your cooperation
Happy coding

Regards

**Comment by e8johan** [comment]
Hi Eadwin,

Thanks for the fix - I will continue down the trippleslash branch and document it as the correct way of doing things.

Cheers!

**Comment by e8johan** [comment]
PS. Do you want me to close this one? I'm ok with closing it as 2.3.3 solves the issue.
