### ISSUE TITLE
STATIC_ROOT / COMPRESS_ROOT missing in Readme.md

### ISSUE THREAD

**Issue by nerdoc** [eadwinCode/django-compressor-parceljs#7]
Hi, I just try to get a Vue example running, without success by now.
Just one thing: STATIC_ROOT / COMPRESS_ROOT has to be set, else `./manage.py compress` complains. Could you add that to your readme, like

```
STATIC_ROOT = BASEDIR / "static"
```
Thanks

**Comment by eadwinCode** [comment]
Thanks Christian, I have done that

**Comment by nerdoc** [comment]
Thanks. But this is not all. The vue part does not work at ll, I still did not get django-compressor-parceljs to work yet. The Readme seems to be not enough, and lacks of some settings (that I don't know)

I would like to help as I appreciate this work very much and need this project as base.
How can I help? Should I open a new issue for this problem?
Did you ever try the vue version from scratch (without knowledge of your work?) - because there is something missing.

**Comment by nerdoc** [comment]
> From django-compressor settings, the value of COMPRESS_ENABLED = !DEBUG, in settings.py.
e.g. ehat do you mean with that?
according to [dj. compressor](https://django-compressor.readthedocs.io/en/stable/settings/) , better change it to:

> Django-compressor per default sets COMPRESS_ENABLED to the opposite of DEBUG.

Is that so?
Then add, 
> if you want to enable  COMPRESS_ENABLED during debug, you have to explicitly set it to `True`.

If you want a PR, anytime, just tell me.

**Comment by eadwinCode** [comment]
If you are having issues setting up the app then you might need to use the
docker-compose.yml file to boot up the app

Regards

**Comment by nerdoc** [comment]
... and many other problems...
`npm -g install parcel` does not work, as npm doesn't seem to install the parcel bin correctly.
`yarn global add parcel` works correctly.

And even then, `./manage.py compress` fails:

```
CommandError: An error occurred during rendering /home/christian/tmp/dcp/core/templates/index.html: Unable to apply ParserFilterJS (parcel build {file_name} --no-source-maps --no-autoinstall --no-content-hash -d {dir} --out-file {outfile})
🚨  /home/christian/tmp/dcp/static/js/index.js: Unknown version 87 of edge
```
> Unknown version 87 of edge

--> WTF? needed days for that.
You have to install parcel locally, in your package, not globally. Seems to be a bug. And add the node_modules/.bin directory to your $PATH

AH, and Docker is  a no-go for me. I'd just like to have it "native".
So If you like I can help improving the Readme... if not (which I could understand too), I'll create a fork, or maybe better a cookiecutter template for django-compress-parceljs-vue...

**Comment by eadwinCode** [comment]
Oh okay. You can do what you have to do. I will look at the PR when you are
done.

**Comment by nerdoc** [comment]
Sorry, I don't have time ATM.
